---
name: Build Tests
on:
  pull_request:
    types:
      - opened
  release:
    types:
      - published
  schedule:
    - cron: 0 0 * * *
jobs:
  build:
    runs-on: ubuntu-latest
    name: Run the ufs_pyutils build-tests.
    steps:
      - name: Build and install Python dependencies.
        run: >
          $(which wget) --no-check-certificate
          https://repo.anaconda.com/miniconda/Miniconda3-py39_4.10.3-Linux-x86_64.sh

          $(which sh) Miniconda3-py39_4.10.3-Linux-x86_64.sh -b -p miniconda

          $(which python) -m pip install --upgrade pip
      - name: Checkout ufs_pyutils.
        uses: actions/checkout@v2
        with:
          path: ufs_pyutils
      - name: Build ufs_pyutils.
        run: >
          cd ${GITHUB_WORKSPACE}/ufs_pyutils/

          $(which python) ${GITHUB_WORKSPACE}/ufs_pyutils/setup.py build

          $(which python)  ${GITHUB_WORKSPACE}/ufs_pyutils/setup.py install --user
