---
name: Python Coding Standards
on:
  pull_request:
    types:
      - opened
  release:
    types:
      - published
  schedule:
    - cron: 0 0 * * *
jobs:
  build:
    runs-on: ubuntu-latest
    name: Run Python coding standards check.
    steps:
      - name: Build and install Python dependencies
        run: >
          $(which wget) --no-check-certificate
          https://repo.anaconda.com/miniconda/Miniconda3-py39_4.10.3-Linux-x86_64.sh

          $(which sh) Miniconda3-py39_4.10.3-Linux-x86_64.sh -b -p miniconda

          $(which python) -m pip install --upgrade pip

          $(which pip) install pycodestyle
      - name: Checkout ufs_pyutils.
        uses: actions/checkout@v2
        with:
          path: ufs_pyutils
      - name: Run pycodestyle application.
        run: >
          cd ${GITHUB_WORKSPACE}/ufs_pyutils

          $(which pycodestyle) -v --config ${GITHUB_WORKSPACE}/ufs_pyutils/pycodestyle confs

          $(which pycodestyle) -v --config ${GITHUB_WORKSPACE}/ufs_pyutils/pycodestyle ioapps

          $(which pycodestyle) -v --config ${GITHUB_WORKSPACE}/ufs_pyutils/pycodestyle scripts

          $(which pycodestyle) -v --config ${GITHUB_WORKSPACE}/ufs_pyutils/pycodestyle tools

          $(which pycodestyle) -v --config ${GITHUB_WORKSPACE}/ufs_pyutils/pycodestyle utils
